### ISSUE TITLE
Expand possibilities for URL patterns

### ISSUE THREAD

**Issue by espen42** [enonic/lib-router#37]
Lib-router can be set up with a catch-group pattern, for example `libRouter.get('/asset/{path:.+}', req => ...`. This will respond to requests to urls *below* that, such as _<rootUrl>/asset/css/styles.css_ etc, and add `.pathParams.path` to the `request` object, with whatever value is after the slash (`"css/styles.css"`).

But this pattern requires both the slash (after `asset`) and something more after that in the url. If there's no slash-separated sub-uri, this route won't kick in at all. [lib-static](https://github.com/enonic/lib-static/issues/99) has a usage scenario (index fallbacks) which requires a route to not only catch sub-uris this way, but also the root itself - with a trailing slash *and* without one (and to be able to separate between those scenarios in the resulting`request` object):
- _<rootUrl>/asset/_
- _<rootUrl>/asset_

It seems impossible to define a catch-group pattern for this in lib-router?

This is possible with controller mappings, though: they are able to use a regex pattern like `<pattern>/asset(/.*)?$</pattern>`. It seems lib-router is just a bit more picky on the patterns it accepts.

From the point of view of lib-static, an ideal solution would be to allow a pattern to start without a slash before it so that the slash can be part of the group - for example `libRouter.get('/asset{path: /.+}', req => ...`

**Comment by rymsha** [comment]
Current implementation strips away trailing slashes - so it is impossible to defile a pattern that would match `/asset/`, but not `/asset`
With a fix, developers can write pattern `/asset/?` - that would be (almost) like old behavior.
`/asset` - won't match `/asset/`  anymore
